server.port=8083

spring.datasource.url=jdbc:postgresql://postgres-power:5432/power_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true