server.port=8085

spring.data.redis.host=redis-bot
spring.data.redis.port=6379
telegram.bot.name=stalker_pc_builder_bot
telegram.bot.token=8609972937:AAFRlAq7Zttl42Cn8NpDJ8wqPLZ3R3wY8YY

# ???? ??????
spring.datasource.url=jdbc:postgresql://postgres-bot:5432/bot_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# ????? ?????? ??? ?????? ???????? bot_users
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
spring.main.web-application-type=servlet